[package]
name = "ding"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.87"
chrono = "0.4.38"
clap = { version = "4.5.17", features = ["derive"] }
reqwest = "0.12.7"
tokio = { version = "1.40.0", features = ["full"] }
